// Autogenerated lesson data — 60 lessons
const LESSONS = [
  {
    "id": 1,
    "month": 1,
    "week": 1,
    "title_kg": "Кирүү сабак / Тааныштыруу",
    "title_ru": "Вводное занятие / Знакомство",
    "material_kg": "IT дүйнөсү деген эмне, сайт кантип иштейт, программист деген ким, frontend жана браузер кантип иштейт, career roadmap. Мугалим менен таанышуу. Компьютердик негизги көндүмдөр: мыш/клавиатура менен иштөө, файл менеджер, браузерде табды башкаруу. Практика: VS Code орнотуу, ноутбукту окууга даярдоо, typing.com сайтында сабатту жазуу машыгуусун баштоо.",
    "material_ru": "Что такое мир IT, как работает сайт, кто такой программист, что такое frontend и как работает браузер, карьерный roadmap. Знакомство с преподавателем. Базовые компьютерные навыки: работа с мышью/клавиатурой, файловый менеджер, управление вкладками браузера. Практика: установка VS Code, подготовка ноутбука к учёбе, начало тренировки слепой печати на typing.com.",
    "homework_kg": "Typing.com сайтында күнүнө 15 мүнөт жазуу машыгуусун жасоо (жумасына эң аз 5 жолу).",
    "homework_ru": "Заниматься тренировкой печати на typing.com по 15 минут в день (минимум 5 раз в неделю).",
    "video": "https://www.youtube.com/embed/hrbetmFxOak",
    "links": [
      {
        "l_kg": "🔗 VS Code жүктөп алуу",
        "l_ru": "🔗 Скачать VS Code",
        "href": "https://code.visualstudio.com/download"
      },
      {
        "l_kg": "🔗 Typing.com (жазуу машыгуусу)",
        "l_ru": "🔗 Typing.com (тренировка печати)",
        "href": "https://www.typing.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 2,
    "month": 1,
    "week": 1,
    "title_kg": "HTML: текст жана сүрөт",
    "title_ru": "HTML: текст и изображения",
    "material_kg": "HTML негиздери: документтин структурасы, тегдер, текст менен иштөө (h1-h6, p, strong, em), сүрөт коюу (img тег, alt атрибуту).",
    "material_ru": "Основы HTML: структура документа, теги, работа с текстом (h1-h6, p, strong, em), вставка изображений (тег img, атрибут alt).",
    "homework_kg": "Өзү каалаган адам жөнүндө (мисалы, белгилүү адам же өзүңүз) кичине сайт түзүп келүү — тексттер жана сүрөттөр менен.",
    "homework_ru": "Создать небольшой сайт о человеке по своему выбору (например, известная личность или вы сами) — с текстом и изображениями.",
    "video": "https://www.youtube.com/embed/ypcP7Ypo0HU",
    "links": [
      {
        "l_kg": "🔗 MDN: HTML негиздери",
        "l_ru": "🔗 MDN: Основы HTML",
        "href": "https://developer.mozilla.org/ru/docs/Web/HTML"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 3,
    "month": 1,
    "week": 1,
    "title_kg": "HTML: тизме, шилтеме, select",
    "title_ru": "HTML: списки, ссылки, select",
    "material_kg": "HTML: тизмелер (ul/ol/li), шилтемелер (a), select/option элементи.",
    "material_ru": "HTML: списки (ul/ol/li), ссылки (a), элемент select/option.",
    "homework_kg": "Өзү каалаган темада сайт түзүп келүү: анда тема, текст, сүрөт, шилтемелер жана тизме болушу керек.",
    "homework_ru": "Создать сайт на выбранную тему: в нём должны быть тема, текст, изображение, ссылки и список.",
    "video": "https://www.youtube.com/embed/h0qeYBK__dE",
    "links": [
      {
        "l_kg": "🔗 MDN: select элементи",
        "l_ru": "🔗 MDN: элемент select",
        "href": "https://developer.mozilla.org/ru/docs/Web/HTML/Element/select"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 4,
    "month": 1,
    "week": 1,
    "title_kg": "HTML: формалар",
    "title_ru": "HTML: формы",
    "material_kg": "HTML: формалар, инпут түрлөрү (text, email, password, radio, checkbox), label, button.",
    "material_ru": "HTML: формы, типы input (text, email, password, radio, checkbox), label, button.",
    "homework_kg": "Катталуу формасын түзүп келүү: аты-жөнү, email, пароль, жынысы, шарттарга макулдук (checkbox), акырында «Катталуу» баскычы.",
    "homework_ru": "Создать форму регистрации: имя, email, пароль, пол, согласие с условиями (checkbox), кнопка «Зарегистрироваться» в конце.",
    "video": "https://www.youtube.com/embed/m9gOHsFoWRo",
    "links": [
      {
        "l_kg": "🔗 MDN: HTML формалары",
        "l_ru": "🔗 MDN: Формы HTML",
        "href": "https://developer.mozilla.org/ru/docs/Learn/HTML/Forms"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 5,
    "month": 1,
    "week": 1,
    "title_kg": "CSS негиздери",
    "title_ru": "Основы CSS",
    "material_kg": "CSS негиздери: селекторлор, түс (color), фон (background), өлчөм (width/height).",
    "material_ru": "Основы CSS: селекторы, цвет (color), фон (background), размеры (width/height).",
    "homework_kg": "Селекторлор жардамында 10 текст жасоо — баары ар кандай өлчөмдө, ар кандай түстө жана ар кандай фондо болсун.",
    "homework_ru": "Сделать 10 текстовых блоков с помощью селекторов — все разного размера, цвета и фона.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: CSS негиздери",
        "l_ru": "🔗 MDN: Основы CSS",
        "href": "https://developer.mozilla.org/ru/docs/Learn/CSS/First_steps"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 6,
    "month": 1,
    "week": 2,
    "title_kg": "CSS: border, псевдо-класстар",
    "title_ru": "CSS: border, псевдо-классы",
    "material_kg": "CSS: border, border-radius, псевдо-класстар (:hover, :focus, :nth-child).",
    "material_ru": "CSS: border, border-radius, псевдо-классы (:hover, :focus, :nth-child).",
    "homework_kg": "border-radius колдонуп, сүрөттү жалбырак сыяктуу формага келтирүү.",
    "homework_ru": "С помощью border-radius превратить изображение в форму, похожую на лист.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: псевдо-класстар",
        "l_ru": "🔗 MDN: псевдо-классы",
        "href": "https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-classes"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 7,
    "month": 1,
    "week": 2,
    "title_kg": "CSS: box model, margin/padding",
    "title_ru": "CSS: box model, margin/padding",
    "material_kg": "CSS: box model, margin жана padding (сырткы жана ички отступтар).",
    "material_ru": "CSS: box model, margin и padding (внешние и внутренние отступы).",
    "homework_kg": "Margin/padding колдонуп 3 карточканы 3 башка жерге жайгаштыруу: биринчиси жогору, экинчиси орто, үчүнчүсү сол жакта.",
    "homework_ru": "С помощью margin/padding расположить 3 карточки в 3 разных местах: первая сверху, вторая по центру, третья слева.",
    "video": "https://www.youtube.com/embed/qCsvaFeHpk8",
    "links": [
      {
        "l_kg": "🔗 MDN: Box model",
        "l_ru": "🔗 MDN: Box model",
        "href": "https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/The_box_model"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 8,
    "month": 1,
    "week": 2,
    "title_kg": "CSS: Flexbox",
    "title_ru": "CSS: Flexbox",
    "material_kg": "CSS: Flexbox — толук практика менен.",
    "material_ru": "CSS: Flexbox — с полной практикой.",
    "homework_kg": "Бул тапшырма мугалим тарабынан өзүнчө берилет (даярдалып жатат).",
    "homework_ru": "Это задание будет добавлено преподавателем отдельно (готовится).",
    "video": "https://www.youtube.com/embed/l61opibO0Bc",
    "links": [
      {
        "l_kg": "🔗 Flexbox Froggy (оюн)",
        "l_ru": "🔗 Flexbox Froggy (игра)",
        "href": "https://flexboxfroggy.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 9,
    "month": 1,
    "week": 2,
    "title_kg": "CSS: Grid",
    "title_ru": "CSS: Grid",
    "material_kg": "CSS: Grid — толук практика менен.",
    "material_ru": "CSS: Grid — с полной практикой.",
    "homework_kg": "Бул тапшырма мугалим тарабынан өзүнчө берилет (даярдалып жатат).",
    "homework_ru": "Это задание будет добавлено преподавателем отдельно (готовится).",
    "video": "https://www.youtube.com/embed/HG0K7B5SnNA",
    "links": [
      {
        "l_kg": "🔗 Grid Garden (оюн)",
        "l_ru": "🔗 Grid Garden (игра)",
        "href": "https://cssgridgarden.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 10,
    "month": 1,
    "week": 2,
    "title_kg": "CSS: position",
    "title_ru": "CSS: position",
    "material_kg": "CSS: position (static, relative, absolute, fixed, sticky).",
    "material_ru": "CSS: position (static, relative, absolute, fixed, sticky).",
    "homework_kg": "position колдонуп: экрандын үстүндө туруучу (sticky/fixed) menu жана оң ылдый бурчта «жогору чык» баскычын жасоо.",
    "homework_ru": "С помощью position сделать закреплённое (sticky/fixed) меню сверху и кнопку «наверх» в правом нижнем углу.",
    "video": "https://www.youtube.com/embed/cAmb4x0Nzms",
    "links": [
      {
        "l_kg": "🔗 MDN: position",
        "l_ru": "🔗 MDN: position",
        "href": "https://developer.mozilla.org/ru/docs/Web/CSS/position"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 11,
    "month": 1,
    "week": 3,
    "title_kg": "Responsive дизайн",
    "title_ru": "Адаптивный дизайн",
    "material_kg": "Responsive дизайн: media queries, mobile-first подход, адаптация.",
    "material_ru": "Адаптивный дизайн: media queries, mobile-first подход, адаптация.",
    "homework_kg": "Мурунку кайсы бир долбооруңузду mobile, tablet жана desktop үчүн responsive кылып чыгуу.",
    "homework_ru": "Сделать один из ваших прошлых проектов адаптивным для mobile, tablet и desktop.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 web.dev: Responsive дизайн",
        "l_ru": "🔗 web.dev: Адаптивный дизайн",
        "href": "https://web.dev/learn/design/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 12,
    "month": 1,
    "week": 3,
    "title_kg": "CSS: анимация, 3D негизи",
    "title_ru": "CSS: анимация, основы 3D",
    "material_kg": "CSS: transitions жана animations. Кошумча: 3D transform'дун негизги идеясы (кыскача, практикалык мисал менен).",
    "material_ru": "CSS: transitions и animations. Дополнительно: базовая идея 3D transform (кратко, с практическим примером).",
    "homework_kg": "Hover'де анимацияланган баскыч жасоо, кошумча — 3D flip-card эффектин колдонуп кичине карточка жасоо.",
    "homework_ru": "Сделать кнопку с анимацией при hover, дополнительно — карточку с эффектом 3D flip-card.",
    "video": "https://www.youtube.com/embed/6roQR5r5MFQ",
    "links": [
      {
        "l_kg": "🔗 MDN: CSS Animations",
        "l_ru": "🔗 MDN: CSS Animations",
        "href": "https://developer.mozilla.org/ru/docs/Web/CSS/CSS_animations/Using_CSS_animations"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 13,
    "month": 1,
    "week": 3,
    "title_kg": "Bootstrap негиздери",
    "title_ru": "Основы Bootstrap",
    "material_kg": "Bootstrap негиздери: grid системасы, даяр компоненттер (navbar, button, card).",
    "material_ru": "Основы Bootstrap: grid-система, готовые компоненты (navbar, button, card).",
    "homework_kg": "Bootstrap grid жана даяр компоненттерди (navbar, card, button) колдонуп бир бет жасоо.",
    "homework_ru": "Сделать одну страницу с использованием Bootstrap grid и готовых компонентов (navbar, card, button).",
    "video": "https://www.youtube.com/embed/WuPnKFaMQpY",
    "links": [
      {
        "l_kg": "🔗 Bootstrap расмий документация",
        "l_ru": "🔗 Официальная документация Bootstrap",
        "href": "https://getbootstrap.com/docs/5.3/getting-started/introduction/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 14,
    "month": 1,
    "week": 3,
    "title_kg": "Git & GitHub киришүү",
    "title_ru": "Введение в Git & GitHub",
    "material_kg": "Git & GitHub киришүү: Git орнотуу, репозиторий түзүү, init, add, commit, push, .gitignore. Ушул сабактан баштап бардык үй тапшырмалар GitHub'га коммит менен тапшырылат.",
    "material_ru": "Введение в Git & GitHub: установка Git, создание репозитория, init, add, commit, push, .gitignore. Начиная с этого занятия все домашние задания сдаются коммитом на GitHub.",
    "homework_kg": "Жеке GitHub аккаунт ачуу, биринчи репозиторий түзүү жана ушул мезгилге чейинки бардык долбоорлоруңузду push кылуу.",
    "homework_ru": "Создать личный аккаунт на GitHub, первый репозиторий и запушить все свои проекты, сделанные до этого момента.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Learn Git Branching (интерактив)",
        "l_ru": "🔗 Learn Git Branching (интерактив)",
        "href": "https://learngitbranching.js.org/?locale=ru_RU"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 15,
    "month": 1,
    "week": 3,
    "title_kg": "HTML+CSS Долбоор — 1-күн",
    "title_ru": "HTML+CSS Проект — день 1",
    "material_kg": "Долбоор — 1-күн: Figma'дан даяр дизайн боюнча сайттын HTML структурасын жана негизги версткасын түзүү.",
    "material_ru": "Проект — день 1: создание HTML-структуры и базовой вёрстки сайта по готовому дизайну из Figma.",
    "homework_kg": "Долбоордун толук HTML структурасын даярдап бүтүрүү (семантикалык тегдер менен).",
    "homework_ru": "Полностью подготовить HTML-структуру проекта (с использованием семантических тегов).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Figma расмий сайты",
        "l_ru": "🔗 Официальный сайт Figma",
        "href": "https://www.figma.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 16,
    "month": 1,
    "week": 4,
    "title_kg": "HTML+CSS Долбоор — 2-күн",
    "title_ru": "HTML+CSS Проект — день 2",
    "material_kg": "Долбоор — 2-күн: CSS менен стилдештирүү, responsive'ке келтирүү (mobile/tablet/desktop).",
    "material_ru": "Проект — день 2: стилизация с помощью CSS, адаптация под responsive (mobile/tablet/desktop).",
    "homework_kg": "Долбоордун стилдерин аяктап, responsive'ке толук келтирүү.",
    "homework_ru": "Завершить стилизацию проекта и полностью адаптировать под responsive.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Frontend Mentor (челленждер)",
        "l_ru": "🔗 Frontend Mentor (челленджи)",
        "href": "https://www.frontendmentor.io/challenges"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 17,
    "month": 1,
    "week": 4,
    "title_kg": "HTML+CSS Долбоор — 3-күн, деплой",
    "title_ru": "HTML+CSS Проект — день 3, деплой",
    "material_kg": "Долбоор — 3-күн: акыркы тактоолор, долбоорду GitHub'га коммит кылуу жана GitHub Pages'ке деплой кылуу.",
    "material_ru": "Проект — день 3: финальные правки, коммит проекта на GitHub и деплой на GitHub Pages.",
    "homework_kg": "Долбоорду GitHub Pages'ке деплой кылуу жана кыска README жазуу.",
    "homework_ru": "Задеплоить проект на GitHub Pages и написать краткий README.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 GitHub Pages: расмий гид",
        "l_ru": "🔗 GitHub Pages: официальный гайд",
        "href": "https://pages.github.com/"
      }
    ],
    "project": true,
    "exam": false
  },
  {
    "id": 18,
    "month": 1,
    "week": 4,
    "title_kg": "1-АЙДЫН ЭКЗАМЕНИ",
    "title_ru": "ЭКЗАМЕН ЗА 1-Й МЕСЯЦ",
    "material_kg": "1-айдын экзамени: HTML, CSS, Bootstrap жана Git негиздери боюнча текшерүү (теория + практикалык тапшырма).",
    "material_ru": "Экзамен за 1-й месяц: проверка по HTML, CSS, Bootstrap и основам Git (теория + практическое задание).",
    "homework_kg": "Экзаменге даярдануу: 1-4-жумалардын бардык темаларын кайталоо.",
    "homework_ru": "Подготовка к экзамену: повторить все темы 1–4 недель.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Кариера барагын ач",
        "l_ru": "🔗 Открыть страницу Карьера",
        "href": "career.html"
      }
    ],
    "project": true,
    "exam": true
  },
  {
    "id": 19,
    "month": 2,
    "week": 1,
    "title_kg": "JS киришүү: айнымалылар",
    "title_ru": "Введение в JS: переменные",
    "material_kg": "JavaScript киришүү: айнымалылар (let, const), JS кайда жана кантип туташтырылат (script тег).",
    "material_ru": "Введение в JavaScript: переменные (let, const), как и куда подключается JS (тег script).",
    "homework_kg": "Ар кандай маалымат түрүн (сан, сап, logical) сактаган 10 айнымалы жазып, консолго чыгаруу.",
    "homework_ru": "Написать 10 переменных с разными типами данных (число, строка, логический) и вывести их в консоль.",
    "video": "https://www.youtube.com/embed/s1c6BoLz9Ow",
    "links": [
      {
        "l_kg": "🔗 javascript.info (толук курс)",
        "l_ru": "🔗 javascript.info (полный курс)",
        "href": "https://learn.javascript.ru/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 20,
    "month": 2,
    "week": 1,
    "title_kg": "JS: маалымат түрлөрү",
    "title_ru": "JS: типы данных",
    "material_kg": "JS: маалымат түрлөрү (data types), арифметикалык жана логикалык операторлор.",
    "material_ru": "JS: типы данных (data types), арифметические и логические операторы.",
    "homework_kg": "Эки санды алып, +, -, *, / жыйынтыктарын консолго чыгарган мини-калькулятор жазуу.",
    "homework_ru": "Написать мини-калькулятор: взять два числа и вывести в консоль результаты +, -, *, /.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: маалымат түрлөрү",
        "l_ru": "🔗 javascript.info: типы данных",
        "href": "https://learn.javascript.ru/types"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 21,
    "month": 2,
    "week": 1,
    "title_kg": "JS: if/else",
    "title_ru": "JS: if/else",
    "material_kg": "JS: шарттар — if/else, логикалык операторлор.",
    "material_ru": "JS: условия — if/else, логические операторы.",
    "homework_kg": "Жашты киргизип, санына жараша «бала / өспүрүм / чоң адам» деп жазган программа түзүү.",
    "homework_ru": "Написать программу: ввести возраст и вывести «ребёнок / подросток / взрослый» в зависимости от числа.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: if..else",
        "l_ru": "🔗 javascript.info: if..else",
        "href": "https://learn.javascript.ru/ifelse"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 22,
    "month": 2,
    "week": 1,
    "title_kg": "JS: switch/case",
    "title_ru": "JS: switch/case",
    "material_kg": "JS: switch/case.",
    "material_ru": "JS: switch/case.",
    "homework_kg": "Жумасынын күнүн (1-7 сан) киргизип, атын консолго чыгарган switch/case жазуу.",
    "homework_ru": "Написать switch/case: ввести номер дня недели (1-7) и вывести его название в консоль.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: switch",
        "l_ru": "🔗 javascript.info: switch",
        "href": "https://learn.javascript.ru/switch"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 23,
    "month": 2,
    "week": 1,
    "title_kg": "JS: циклдер",
    "title_ru": "JS: циклы",
    "material_kg": "JS: циклдер (for, while, for...of).",
    "material_ru": "JS: циклы (for, while, for...of).",
    "homework_kg": "1ден 100гө чейинки жуп сандардын суммасын циклдин жардамы менен эсептөө.",
    "homework_ru": "С помощью цикла посчитать сумму чётных чисел от 1 до 100.",
    "video": "https://www.youtube.com/embed/L3uE0djkjbA",
    "links": [
      {
        "l_kg": "🔗 javascript.info: циклдер",
        "l_ru": "🔗 javascript.info: циклы",
        "href": "https://learn.javascript.ru/while-for"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 24,
    "month": 2,
    "week": 2,
    "title_kg": "JS: функциялар",
    "title_ru": "JS: функции",
    "material_kg": "JS: функциялар — function declaration, function expression, параметрлер.",
    "material_ru": "JS: функции — function declaration, function expression, параметры.",
    "homework_kg": "Эки санды кошуучу, көбөйтүүчү жана бөлүүчү 3 өзүнчө функция жазуу.",
    "homework_ru": "Написать 3 отдельные функции: для сложения, умножения и деления двух чисел.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: функциялар",
        "l_ru": "🔗 javascript.info: функции",
        "href": "https://learn.javascript.ru/function-basics"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 25,
    "month": 2,
    "week": 2,
    "title_kg": "JS: массив методдору",
    "title_ru": "JS: методы массивов",
    "material_kg": "JS: массивдер жана методдору (map, filter, forEach, reduce) — функцияларды колдонуп.",
    "material_ru": "JS: массивы и их методы (map, filter, forEach, reduce) — с использованием функций.",
    "homework_kg": "Сандар массивинен жуп сандарды filter аркылуу тандап, ар бирин map менен 2ге көбөйтүп жаңы массив чыгаруу.",
    "homework_ru": "Из массива чисел с помощью filter выбрать чётные, затем с помощью map умножить каждое на 2 и вывести новый массив.",
    "video": "https://www.youtube.com/embed/wCEKqxlsVn0",
    "links": [
      {
        "l_kg": "🔗 javascript.info: массив методдору",
        "l_ru": "🔗 javascript.info: методы массивов",
        "href": "https://learn.javascript.ru/array-methods"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 26,
    "month": 2,
    "week": 2,
    "title_kg": "JS: объекттер",
    "title_ru": "JS: объекты",
    "material_kg": "JS: объекттер, this түшүнүгү.",
    "material_ru": "JS: объекты, понятие this.",
    "homework_kg": "Өзүңүз жөнүндө object түзүү (аты, жашы, көндүмдөрдүн массиви) жана маалыматтарын консолго чыгаруу.",
    "homework_ru": "Создать объект о себе (имя, возраст, массив навыков) и вывести данные в консоль.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: объекттер",
        "l_ru": "🔗 javascript.info: объекты",
        "href": "https://learn.javascript.ru/object"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 27,
    "month": 2,
    "week": 2,
    "title_kg": "DOM негиздери",
    "title_ru": "Основы DOM",
    "material_kg": "DOM негиздери: элементтерди тандоо жана өзгөртүү (querySelector, classList, addEventListener).",
    "material_ru": "Основы DOM: выбор и изменение элементов (querySelector, classList, addEventListener).",
    "homework_kg": "Баскычты басканда баракчанын фон түсү өзгөргөн кичине бет жасоо.",
    "homework_ru": "Сделать небольшую страницу: при нажатии кнопки меняется цвет фона страницы.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: DOM",
        "l_ru": "🔗 MDN: DOM",
        "href": "https://developer.mozilla.org/ru/docs/Web/API/Document_Object_Model"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 28,
    "month": 2,
    "week": 2,
    "title_kg": "Практика: Counter долбоору",
    "title_ru": "Практика: проект Counter",
    "material_kg": "Практика: Counter долбоору (баскыч менен санды көбөйтүү/азайтуу).",
    "material_ru": "Практика: проект Counter (увеличение/уменьшение числа кнопкой).",
    "homework_kg": "Counter долбоорун аяктап, GitHub'га коммит кылуу.",
    "homework_ru": "Завершить проект Counter и закоммитить на GitHub.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 freeCodeCamp: JS долбоорлору",
        "l_ru": "🔗 freeCodeCamp: JS-проекты",
        "href": "https://www.freecodecamp.org/news/tag/javascript-projects/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 29,
    "month": 2,
    "week": 3,
    "title_kg": "Практика: To-Do List",
    "title_ru": "Практика: To-Do List",
    "material_kg": "Практика: To-Do List долбоору (кошуу, белгилөө, өчүрүү).",
    "material_ru": "Практика: проект To-Do List (добавление, отметка, удаление).",
    "homework_kg": "To-Do List'ке «баарын өчүрүү» баскычын жана тапшырмалардын санын көрсөткөн counter кошуу.",
    "homework_ru": "Добавить в To-Do List кнопку «удалить всё» и счётчик количества задач.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Frontend Mentor (челленждер)",
        "l_ru": "🔗 Frontend Mentor (челленджи)",
        "href": "https://www.frontendmentor.io/challenges"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 30,
    "month": 2,
    "week": 3,
    "title_kg": "setInterval / setTimeout",
    "title_ru": "setInterval / setTimeout",
    "material_kg": "setInterval / setTimeout — практикалык долбоор (мисалы, countdown-таймер же слайдер).",
    "material_ru": "setInterval / setTimeout — практический проект (например, countdown-таймер или слайдер).",
    "homework_kg": "Секунда сайын өзгөргөн countdown-таймер (мисалы, 60 секунддан 0го чейин) жасоо.",
    "homework_ru": "Сделать countdown-таймер, который обновляется каждую секунду (например, с 60 до 0).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: setInterval",
        "l_ru": "🔗 MDN: setInterval",
        "href": "https://developer.mozilla.org/ru/docs/Web/API/setInterval"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 31,
    "month": 2,
    "week": 3,
    "title_kg": "Себет долбоору — 1-күн",
    "title_ru": "Проект корзины — день 1",
    "material_kg": "Долбоор — 1-күн: Figma боюнча себети (cart) бар онлайн-дүкөндүн HTML/CSS версткасы.",
    "material_ru": "Проект — день 1: HTML/CSS вёрстка интернет-магазина с корзиной (cart) по Figma.",
    "homework_kg": "Дүкөндүн версткасын толук аяктоо (товарлар тизмеси, себет UI).",
    "homework_ru": "Полностью завершить вёрстку магазина (список товаров, UI корзины).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Figma расмий сайты",
        "l_ru": "🔗 Официальный сайт Figma",
        "href": "https://www.figma.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 32,
    "month": 2,
    "week": 3,
    "title_kg": "Себет долбоору — 2-күн",
    "title_ru": "Проект корзины — день 2",
    "material_kg": "Долбоор — 2-күн: себетке товар кошуу логикасы (JS), localStorage'го сактоо.",
    "material_ru": "Проект — день 2: логика добавления товара в корзину (JS), сохранение в localStorage.",
    "homework_kg": "Себетке кошуу логикасын толуктап, барактын жаңылангандан кийин да маалымат сакталышын текшерүү.",
    "homework_ru": "Доработать логику добавления в корзину и проверить, что данные сохраняются после обновления страницы.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: Web Storage API",
        "l_ru": "🔗 MDN: Web Storage API",
        "href": "https://developer.mozilla.org/ru/docs/Web/API/Web_Storage_API"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 33,
    "month": 2,
    "week": 3,
    "title_kg": "Себет долбоору — 3-күн",
    "title_ru": "Проект корзины — день 3",
    "material_kg": "Долбоор — 3-күн: себеттен товар өчүрүү, жалпы суммасын эсептөө, долбоорду аяктоо жана деплой кылуу.",
    "material_ru": "Проект — день 3: удаление товара из корзины, подсчёт итоговой суммы, завершение проекта и деплой.",
    "homework_kg": "Себеттен өчүрүү функциясын кошуп, долбоорду GitHub Pages'ке деплой кылуу.",
    "homework_ru": "Добавить функцию удаления из корзины и задеплоить проект на GitHub Pages.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 GitHub Pages: расмий гид",
        "l_ru": "🔗 GitHub Pages: официальный гайд",
        "href": "https://pages.github.com/"
      }
    ],
    "project": true,
    "exam": false
  },
  {
    "id": 34,
    "month": 2,
    "week": 4,
    "title_kg": "Fetch API: then/catch",
    "title_ru": "Fetch API: then/catch",
    "material_kg": "Fetch API: then/catch менен суроо-талап жиберүү, публикалык API менен иштөө.",
    "material_ru": "Fetch API: отправка запроса через then/catch, работа с публичным API.",
    "homework_kg": "Публикалык API'ден маалымат алып, консолго толук чыгаруу.",
    "homework_ru": "Получить данные с публичного API и полностью вывести их в консоль.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Public APIs (акысыз API тизмеси)",
        "l_ru": "🔗 Public APIs (список бесплатных API)",
        "href": "https://github.com/public-apis/public-apis"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 35,
    "month": 2,
    "week": 4,
    "title_kg": "async/await",
    "title_ru": "async/await",
    "material_kg": "async/await, error handling (try/catch).",
    "material_ru": "async/await, обработка ошибок (try/catch).",
    "homework_kg": "Мурунку fetch кодун async/await менен кайра жазып, try/catch менен ката иштетүүнү кошуу.",
    "homework_ru": "Переписать предыдущий код fetch на async/await и добавить обработку ошибок через try/catch.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: async/await",
        "l_ru": "🔗 javascript.info: async/await",
        "href": "https://learn.javascript.ru/async-await"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 36,
    "month": 2,
    "week": 4,
    "title_kg": "Практика: Fetch service",
    "title_ru": "Практика: Fetch service",
    "material_kg": "Практика: бир API'ден 4 башка суроо-талапты (fetch service) чогуу иштетип, бир долбоордо колдонуу.",
    "material_ru": "Практика: сервис из 4 разных запросов (fetch service) к одному API, использование в одном проекте.",
    "homework_kg": "Fetch service'ти толуктап, 4 суроо-талаптын натыйжаларын экранга чыгаруу.",
    "homework_ru": "Доработать fetch service и вывести на экран результаты всех 4 запросов.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 MDN: Fetch API",
        "l_ru": "🔗 MDN: Fetch API",
        "href": "https://developer.mozilla.org/ru/docs/Web/API/Fetch_API"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 37,
    "month": 2,
    "week": 4,
    "title_kg": "Фильтр/издөө долбоору — 1-күн",
    "title_ru": "Проект фильтра/поиска — день 1",
    "material_kg": "Долбоор — 1-күн: фильтр жана издөө (search) функциясы бар долбоордун HTML/CSS версткасы.",
    "material_ru": "Проект — день 1: HTML/CSS вёрстка проекта с функциями фильтра и поиска (search).",
    "homework_kg": "Долбоордун версткасын толук аяктоо.",
    "homework_ru": "Полностью завершить вёрстку проекта.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Frontend Mentor (челленждер)",
        "l_ru": "🔗 Frontend Mentor (челленджи)",
        "href": "https://www.frontendmentor.io/challenges"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 38,
    "month": 2,
    "week": 4,
    "title_kg": "Фильтр/издөө долбоору — 2-күн",
    "title_ru": "Проект фильтра/поиска — день 2",
    "material_kg": "Долбоор — 2-күн: фильтр функциясын JS менен ишке ашыруу (массив методдору менен).",
    "material_ru": "Проект — день 2: реализация функции фильтра на JS (с использованием методов массива).",
    "homework_kg": "Фильтр функциясын толуктап, ар кайсы категория боюнча иштешин текшерүү.",
    "homework_ru": "Доработать функцию фильтра и проверить её работу по разным категориям.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 javascript.info: массив методдору",
        "l_ru": "🔗 javascript.info: методы массивов",
        "href": "https://learn.javascript.ru/array-methods"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 39,
    "month": 2,
    "week": 5,
    "title_kg": "Фильтр/издөө долбоору — 3-күн",
    "title_ru": "Проект фильтра/поиска — день 3",
    "material_kg": "Долбоор — 3-күн: издөө (search) функциясын ишке ашыруу, долбоорду аяктоо жана GitHub'га коммит.",
    "material_ru": "Проект — день 3: реализация функции поиска (search), завершение проекта и коммит на GitHub.",
    "homework_kg": "Издөө функциясын кошуп, долбоорду GitHub Pages'ке деплой кылуу.",
    "homework_ru": "Добавить функцию поиска и задеплоить проект на GitHub Pages.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 GitHub Pages: расмий гид",
        "l_ru": "🔗 GitHub Pages: официальный гайд",
        "href": "https://pages.github.com/"
      }
    ],
    "project": true,
    "exam": false
  },
  {
    "id": 40,
    "month": 2,
    "week": 5,
    "title_kg": "Git тереңирээк",
    "title_ru": "Git глубже",
    "material_kg": "Git тереңирээк: branch, merge, конфликттерди чечүү, Pull Request жумуш процесси (workflow).",
    "material_ru": "Git глубже: branch, merge, разрешение конфликтов, workflow Pull Request.",
    "homework_kg": "Жаңы branch түзүп, анда өзгөртүү киргизип, негизги branch'ка merge кылуу.",
    "homework_ru": "Создать новую branch, внести изменения и сделать merge в основную branch.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 GitHub Skills (расмий курс)",
        "l_ru": "🔗 GitHub Skills (официальный курс)",
        "href": "https://skills.github.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 41,
    "month": 3,
    "week": 1,
    "title_kg": "React'ка киришүү",
    "title_ru": "Введение в React",
    "material_kg": "React'ка киришүү: компоненттер, JSX синтаксиси.",
    "material_ru": "Введение в React: компоненты, синтаксис JSX.",
    "homework_kg": "Vite менен жаңы React долбоор түзүп, 3 кичине компонент (мисалы, Header, Footer, Card) жасоо.",
    "homework_ru": "Создать новый React-проект через Vite и сделать 3 маленьких компонента (например, Header, Footer, Card).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: расмий гид",
        "l_ru": "🔗 react.dev: официальный гайд",
        "href": "https://react.dev/learn"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 42,
    "month": 3,
    "week": 1,
    "title_kg": "Props жана State",
    "title_ru": "Props и State",
    "material_kg": "Props жана State түшүнүгү.",
    "material_ru": "Понятия Props и State.",
    "homework_kg": "Props аркылуу маалымат өткөрүүчү 3 карточка компонентин (ар бирине ат, сүрөт, баа) жасоо.",
    "homework_ru": "Сделать 3 карточки-компонента, передающих данные через props (имя, изображение, цена для каждой).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Props",
        "l_ru": "🔗 react.dev: Props",
        "href": "https://react.dev/learn/passing-props-to-a-component"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 43,
    "month": 3,
    "week": 1,
    "title_kg": "React event'тер, conditional rendering",
    "title_ru": "React события, conditional rendering",
    "material_kg": "React'та event'терди кармоо, conditional rendering.",
    "material_ru": "Обработка событий в React, conditional rendering.",
    "homework_kg": "Баскычты басканда текст көрүнүп/жашырылган (show/hide) компонент жасоо.",
    "homework_ru": "Сделать компонент, где при нажатии кнопки текст показывается/скрывается (show/hide).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Events",
        "l_ru": "🔗 react.dev: события",
        "href": "https://react.dev/learn/responding-to-events"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 44,
    "month": 3,
    "week": 1,
    "title_kg": "Тизмелер жана key",
    "title_ru": "Списки и key",
    "material_kg": "Conditional rendering, тизмелер жана key.",
    "material_ru": "Conditional rendering, списки и key.",
    "homework_kg": "Массивден .map() менен тизме элементтерин рендер кылган компонент жасоо (key менен).",
    "homework_ru": "Сделать компонент, рендерящий элементы списка из массива через .map() (с использованием key).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: тизмелерди рендер кылуу",
        "l_ru": "🔗 react.dev: рендеринг списков",
        "href": "https://react.dev/learn/rendering-lists"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 45,
    "month": 3,
    "week": 1,
    "title_kg": "useState hook",
    "title_ru": "Хук useState",
    "material_kg": "useState hook — практика менен.",
    "material_ru": "Хук useState — с практикой.",
    "homework_kg": "useState колдонуп, like-баскычы (лайк саны өзгөргөн) компонент жасоо.",
    "homework_ru": "С помощью useState сделать компонент с кнопкой like (изменяется счётчик лайков).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: useState",
        "l_ru": "🔗 react.dev: useState",
        "href": "https://react.dev/reference/react/useState"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 46,
    "month": 3,
    "week": 2,
    "title_kg": "useEffect hook",
    "title_ru": "Хук useEffect",
    "material_kg": "useEffect hook — lifecycle, side effect'тер.",
    "material_ru": "Хук useEffect — lifecycle, side effects.",
    "homework_kg": "useEffect колдонуп, компонент ачылганда API'ден маалымат алып келген компонент жасоо.",
    "homework_ru": "С помощью useEffect сделать компонент, загружающий данные с API при открытии.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: useEffect",
        "l_ru": "🔗 react.dev: useEffect",
        "href": "https://react.dev/reference/react/useEffect"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 47,
    "month": 3,
    "week": 2,
    "title_kg": "React формалары",
    "title_ru": "Формы в React",
    "material_kg": "Формалар менен иштөө (controlled components).",
    "material_ru": "Работа с формами (controlled components).",
    "homework_kg": "useState менен башкарылган (controlled) катталуу формасын React'та жасоо.",
    "homework_ru": "Сделать управляемую (controlled) форму регистрации в React с использованием useState.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: форма элементтери",
        "l_ru": "🔗 react.dev: элементы форм",
        "href": "https://react.dev/reference/react-dom/components/input"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 48,
    "month": 3,
    "week": 2,
    "title_kg": "Компоненттерди бөлүү",
    "title_ru": "Разбиение компонентов",
    "material_kg": "Компоненттерди бөлүктөргө бөлүү, кайра колдонуу (reusability).",
    "material_ru": "Разбиение компонентов, переиспользование (reusability).",
    "homework_kg": "Чоң бир компонентти 3-4 кичине кайра колдонула турган (reusable) компонентке бөлүү.",
    "homework_ru": "Разбить один большой компонент на 3-4 маленьких переиспользуемых (reusable) компонента.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Thinking in React",
        "l_ru": "🔗 react.dev: Thinking in React",
        "href": "https://react.dev/learn/thinking-in-react"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 49,
    "month": 3,
    "week": 2,
    "title_kg": "Практика: Todo App (React)",
    "title_ru": "Практика: Todo App (React)",
    "material_kg": "Практика: Todo App (React менен кайра курулушу).",
    "material_ru": "Практика: Todo App (переписываем на React).",
    "homework_kg": "Мурда Vanilla JS'те жасалган Todo List долбоорун React менен кайра куруу.",
    "homework_ru": "Переписать ранее сделанный на Vanilla JS проект Todo List с использованием React.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Frontend Mentor: React челленждери",
        "l_ru": "🔗 Frontend Mentor: React-челленджи",
        "href": "https://www.frontendmentor.io/challenges?technologies=react"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 50,
    "month": 3,
    "week": 2,
    "title_kg": "React Router",
    "title_ru": "React Router",
    "material_kg": "React Router: беттер аралык навигация, dynamic routes.",
    "material_ru": "React Router: навигация между страницами, dynamic routes.",
    "homework_kg": "Кеминде 3 беттен (Home, About, Contact) турган React Router менен навигация жасоо.",
    "homework_ru": "Сделать навигацию с React Router из минимум 3 страниц (Home, About, Contact).",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 React Router расмий сайты",
        "l_ru": "🔗 Официальный сайт React Router",
        "href": "https://reactrouter.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 51,
    "month": 3,
    "week": 3,
    "title_kg": "Custom hooks",
    "title_ru": "Custom hooks",
    "material_kg": "Custom hooks түзүү.",
    "material_ru": "Создание custom hooks.",
    "homework_kg": "useLocalStorage сыяктуу жөнөкөй бир custom hook жазып, долбоордо колдонуу.",
    "homework_ru": "Написать простой custom hook (например, useLocalStorage) и использовать его в проекте.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Custom Hooks",
        "l_ru": "🔗 react.dev: Custom Hooks",
        "href": "https://react.dev/learn/reusing-logic-with-custom-hooks"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 52,
    "month": 3,
    "week": 3,
    "title_kg": "Context API",
    "title_ru": "Context API",
    "material_kg": "Context API: глобалдык state менен иштөө.",
    "material_ru": "Context API: работа с глобальным state.",
    "homework_kg": "Context API колдонуп, бүт долбоор боюнча тема (light/dark mode) которгуч жасоо.",
    "homework_ru": "С помощью Context API сделать переключатель темы (light/dark mode) для всего проекта.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Context",
        "l_ru": "🔗 react.dev: Context",
        "href": "https://react.dev/learn/passing-data-deeply-with-context"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 53,
    "month": 3,
    "week": 3,
    "title_kg": "Firebase: Authentication",
    "title_ru": "Firebase: Authentication",
    "material_kg": "Firebase киришүү: долбоор түзүү, Firebase Authentication менен катталуу/кирүү.",
    "material_ru": "Введение в Firebase: создание проекта, регистрация/вход через Firebase Authentication.",
    "homework_kg": "Firebase долбоорун түзүп, email/пароль менен катталуу жана кирүү функцияларын иштетип чыгуу.",
    "homework_ru": "Создать проект Firebase и реализовать функции регистрации и входа по email/паролю.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Firebase Auth документация",
        "l_ru": "🔗 Документация Firebase Auth",
        "href": "https://firebase.google.com/docs/auth"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 54,
    "month": 3,
    "week": 3,
    "title_kg": "Firebase: Firestore",
    "title_ru": "Firebase: Firestore",
    "material_kg": "Firebase Firestore: маалыматтарды сактоо, окуу жана жаңыртуу.",
    "material_ru": "Firebase Firestore: сохранение, чтение и обновление данных.",
    "homework_kg": "Firestore'го маалымат кошуп, аны React компонентинде тизме түрүндө көрсөтүү.",
    "homework_ru": "Добавить данные в Firestore и вывести их списком в компоненте React.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Firebase Firestore документация",
        "l_ru": "🔗 Документация Firebase Firestore",
        "href": "https://firebase.google.com/docs/firestore"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 55,
    "month": 3,
    "week": 3,
    "title_kg": "Практика: Firebase долбоору",
    "title_ru": "Практика: проект с Firebase",
    "material_kg": "Практика: Firebase Authentication жана Firestore колдонгон кичине долбоор.",
    "material_ru": "Практика: небольшой проект с использованием Firebase Authentication и Firestore.",
    "homework_kg": "Катталуу/кирүү жана маалымат сактоо иштеген кичине долбоорду аяктоо.",
    "homework_ru": "Завершить небольшой проект с работающей регистрацией/входом и сохранением данных.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Firebase расмий документация",
        "l_ru": "🔗 Официальная документация Firebase",
        "href": "https://firebase.google.com/docs"
      }
    ],
    "project": true,
    "exam": false
  },
  {
    "id": 56,
    "month": 3,
    "week": 4,
    "title_kg": "Деплой: Vercel",
    "title_ru": "Деплой: Vercel",
    "material_kg": "Деплой: React долбоорун Vercel'ге чыгаруу.",
    "material_ru": "Деплой: публикация React-проекта на Vercel.",
    "homework_kg": "Мурунку Firebase долбоорун Vercel'ге деплой кылуу.",
    "homework_ru": "Задеплоить предыдущий проект с Firebase на Vercel.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Vercel документация",
        "l_ru": "🔗 Документация Vercel",
        "href": "https://vercel.com/docs"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 57,
    "month": 3,
    "week": 4,
    "title_kg": "Финалдык долбоор — 1-күн",
    "title_ru": "Финальный проект — день 1",
    "material_kg": "Финалдык долбоор — 1-күн: долбоордун негизин куруу, компоненттерди бөлүү, архитектураны пландоо.",
    "material_ru": "Финальный проект — день 1: закладка основы проекта, разбиение на компоненты, планирование архитектуры.",
    "homework_kg": "Финалдык долбоордун компоненттеринин структурасын (component tree) чийип, негизин куруу.",
    "homework_ru": "Нарисовать структуру компонентов (component tree) финального проекта и заложить основу.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 react.dev: Thinking in React",
        "l_ru": "🔗 react.dev: Thinking in React",
        "href": "https://react.dev/learn/thinking-in-react"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 58,
    "month": 3,
    "week": 4,
    "title_kg": "Финалдык долбоор — 2-күн",
    "title_ru": "Финальный проект — день 2",
    "material_kg": "Финалдык долбоор — 2-күн: Firebase интеграция (Auth/Firestore), стилдештирүү.",
    "material_ru": "Финальный проект — день 2: интеграция Firebase (Auth/Firestore), стилизация.",
    "homework_kg": "Долбоорго Firebase'ти туташтырып, негизги стилдерди аяктоо.",
    "homework_ru": "Подключить Firebase к проекту и завершить основную стилизацию.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Firebase расмий документация",
        "l_ru": "🔗 Официальная документация Firebase",
        "href": "https://firebase.google.com/docs"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 59,
    "month": 3,
    "week": 4,
    "title_kg": "Финалдык долбоор — 3-күн",
    "title_ru": "Финальный проект — день 3",
    "material_kg": "Финалдык долбоор — 3-күн: тестирлөө, Vercel'ге деплой, README жазуу.",
    "material_ru": "Финальный проект — день 3: тестирование, деплой на Vercel, написание README.",
    "homework_kg": "Долбоорду толук тестирлеп, Vercel'ге деплой кылып, README жазуу.",
    "homework_ru": "Полностью протестировать проект, задеплоить на Vercel и написать README.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Make a README (гид)",
        "l_ru": "🔗 Make a README (гайд)",
        "href": "https://www.makeareadme.com/"
      }
    ],
    "project": false,
    "exam": false
  },
  {
    "id": 60,
    "month": 3,
    "week": 4,
    "title_kg": "Резюме, портфолио, mock interview",
    "title_ru": "Резюме, портфолио, mock interview",
    "material_kg": "Резюме/портфолиону сунуштоо, junior+ техникалык интервью — mock interview, көп берилүүчү суроолор.",
    "material_ru": "Презентация резюме/портфолио, техническое интервью junior+ — mock interview, частые вопросы.",
    "homework_kg": "Резюмеңизди жана GitHub портфолиоңузду даярдап, кийинки сабакка алып келүү.",
    "homework_ru": "Подготовить резюме и портфолио на GitHub, принести на следующее занятие.",
    "video": "",
    "links": [
      {
        "l_kg": "🔗 Кариера барагын ач",
        "l_ru": "🔗 Открыть страницу Карьера",
        "href": "career.html"
      }
    ],
    "project": true,
    "exam": false
  }
];
